apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-cherry
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing item cherry && sleep 5"]
      restartPolicy: Never
