apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-apple
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c
        image: busybox
        command: ["sh", "-c", "echo Processing item apple && sleep 5"]
      restartPolicy: Never
